"""LaTeX formatting helpers shared by the generated tables and in-text numbers (EN and FR).

Numbers follow the typographic convention of the manuscript language: a decimal point and a
comma thousands separator in English, a decimal comma and a thin-space thousands separator in
French. Every number is wrapped so that it typesets identically in text and in math mode.
Fragments are written into manuscript/<lang>/ssrn/tables/, next to the figures, and are never
edited by hand.
"""
from __future__ import annotations

import math
from pathlib import Path

from src.common.paths import PROJECT_ROOT

STARS = ((0.01, "^{***}"), (0.05, "^{**}"), (0.10, "^{*}"))


def tables_dir(lang: str) -> Path:
    d = PROJECT_ROOT / "manuscript" / lang / "ssrn" / "tables"
    d.mkdir(parents=True, exist_ok=True)
    return d


def write_fragment(lang: str, name: str, body: str) -> Path:
    path = tables_dir(lang) / f"{name}.tex"
    header = f"% Generated by src/figures/tables.py ({lang}). Do not edit by hand.\n"
    path.write_text(header + body, encoding="utf-8")
    return path


def _group(digits: str, lang: str) -> str:
    """Insert the thousands separator into a string of digits."""
    sep = "{,}" if lang == "en" else "\\,"
    out = []
    for i, ch in enumerate(reversed(digits)):
        if i and i % 3 == 0:
            out.append(sep)
        out.append(ch)
    return "".join(reversed(out))


def raw_num(x: float, nd: int, lang: str) -> str:
    """Math-mode body of a number rounded to `nd` decimals (minus sign included)."""
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "\\text{--}"
    if isinstance(x, float) and math.isinf(x):
        return "\\infty"
    s = f"{abs(x):.{nd}f}"
    if float(s) == 0.0:
        neg = False
    else:
        neg = x < 0
    whole, _, frac = s.partition(".")
    whole = _group(whole, lang) if len(whole) >= 4 else whole
    dec = "." if lang == "en" else "{,}"
    body = whole + (dec + frac if frac else "")
    return ("-" if neg else "") + body


def num(x: float, nd: int, lang: str) -> str:
    """A number that typesets the same in text and math mode."""
    return f"\\ensuremath{{{raw_num(x, nd, lang)}}}"


def integer(n: int, lang: str) -> str:
    """A count with the language's thousands separator (grouped from four digits)."""
    s = str(int(n))
    body = _group(s, lang) if len(s) >= 4 else s
    return f"\\ensuremath{{{body}}}"


def stars(p: float) -> str:
    for cut, mark in STARS:
        if p < cut:
            return mark
    return ""


def coef(beta: float, p: float, nd: int, lang: str) -> str:
    """Coefficient with significance stars (two-sided p-value)."""
    return f"${raw_num(beta, nd, lang)}{stars(p)}$"


def se(x: float, nd: int, lang: str) -> str:
    return f"$({raw_num(x, nd, lang)})$"


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


# LaTeX symbol of every structural parameter, as the manuscripts write it (tables and figures).
PARAMETER_SYMBOLS = {
    "eta": "\\eta", "theta_dollar": "\\theta", "gamma": "\\gamma", "import_share": "s",
    "imbalance0": "\\bar{b}", "eta_star": "\\eta^{\\ast}", "chi": "\\chi",
    "portfolio_cost": "\\psi", "sigma": "\\sigma", "theta": "\\xi", "phi_pi": "\\phi_{\\pi}",
    "phi_y": "\\phi_{y}", "max_depreciation": "\\bar{e}", "damping_scale": "\\mu",
}
