"""Shared academic figure style, palette, and save helper.

Every figure of both manuscripts uses one palette with a fixed meaning:

  NAVY   the main series or estimate: event-study coefficients, the tariff and the border
         price, dollar invoicing, and an open capital account;
  BRICK  the comparison series: in the structural figures, capital controls or a closed account;
  GREY   benchmarks, reference lines, and the estimate's confidence region.

A comparison series is also drawn dashed or with a different marker, so figures remain legible
in grayscale and for readers with color-vision deficiencies. Confidence bands and regions are
light grey (GREY_TINT); the light navy and brick tints fill the area under a density. When LaTeX is installed, every label is typeset by LaTeX in Latin
Modern, the font of the manuscripts, and embedded as Type 1 fonts; otherwise the style falls back
to DejaVu Serif with Computer Modern mathematics. Figures are drawn at the text width of the manuscripts
(TEXT_WIDTH inches) and included at the full text width, so that their type matches the size of
the figure notes. French figures use the decimal comma. Figures are generated by code and never
edited by hand.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from src.common.paths import PROJECT_ROOT

os.environ.setdefault("MPLCONFIGDIR", "/tmp/weaker-dollar-matplotlib")

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib import ticker  # noqa: E402

NAVY = "#1f3a5f"
BRICK = "#9b2d2a"
GREY = "#7a7a7a"
NAVY_TINT = "#d3dbe6"
BRICK_TINT = "#eed5d2"
GREY_TINT = "#e6e6e6"
INK = "#1a1a1a"

TEXT_WIDTH = 6.2  # inches: A4 with 2.6 cm margins
LANGS = ("en", "fr")
SERIF_FALLBACK = "DejaVu Serif"
LATEX_PREAMBLE = r"\usepackage[T1]{fontenc}\usepackage{lmodern}\usepackage{amsmath}"


def _latex_available() -> bool:
    """LaTeX, dvipng (for the PNG previews), and the Latin Modern package are all present."""
    if not all(shutil.which(tool) for tool in ("latex", "dvipng", "kpsewhich")):
        return False
    try:
        found = subprocess.run(["kpsewhich", "lmodern.sty"], capture_output=True, text=True,
                               check=False).stdout.strip()
    except OSError:
        return False
    return bool(found)


def apply_style() -> None:
    latex = _latex_available()
    plt.rcParams.update({
        "text.usetex": latex,
        "text.latex.preamble": LATEX_PREAMBLE,
        "font.family": "serif",
        "font.serif": ["Computer Modern Roman"] if latex else [SERIF_FALLBACK],
        "mathtext.fontset": "cm", "font.size": 9, "axes.labelsize": 9,
        "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8,
        "figure.facecolor": "white", "axes.facecolor": "white", "savefig.facecolor": "white",
        "axes.edgecolor": INK, "axes.labelcolor": INK, "text.color": INK,
        "xtick.color": INK, "ytick.color": INK, "axes.linewidth": 0.6,
        "xtick.major.width": 0.6, "ytick.major.width": 0.6,
        "xtick.major.size": 3.0, "ytick.major.size": 3.0,
        "xtick.direction": "out", "ytick.direction": "out",
        "axes.spines.top": False, "axes.spines.right": False, "axes.grid": False,
        "legend.frameon": False, "legend.handlelength": 2.2,
        "lines.linewidth": 1.3, "lines.markersize": 3.5,
        "axes.formatter.use_mathtext": True, "axes.unicode_minus": True,
        "pdf.fonttype": 42, "figure.dpi": 150, "savefig.dpi": 300,
    })


class _DecimalComma(ticker.ScalarFormatter):
    """Tick labels with the French decimal comma."""

    def __call__(self, x, pos=None):
        return super().__call__(x, pos).replace(".", "{,}")


def localize(ax, lang: str) -> None:
    """Use the decimal comma on both axes of a French figure."""
    if lang == "fr":
        for axis in (ax.xaxis, ax.yaxis):
            if isinstance(axis.get_major_formatter(), ticker.ScalarFormatter):
                axis.set_major_formatter(_DecimalComma())


def number_labels(values, nd: int, lang: str, group: bool = False) -> list[str]:
    """Tick labels in mathtext: true minus sign, the language's decimal mark, and, when
    `group` is set, the thousands separator (comma in English, thin space in French)."""
    out = []
    for v in values:
        body = f"{abs(v):,.{nd}f}" if group else f"{abs(v):.{nd}f}"
        body = body.replace(",", "\\," if lang == "fr" else "{,}")
        if lang == "fr":
            body = body.replace(".", "{,}")
        sign = "-" if v < 0 and round(abs(v), nd) > 0 else ""
        out.append(f"${sign}{body}$")
    return out


def reference_line(ax, value: float = 0.0, axis: str = "h") -> None:
    """A thin dashed grey reference line at `value` (zero, or an event date on the x axis)."""
    kw = {"color": GREY, "lw": 0.6, "ls": (0, (4, 3)), "zorder": 1}
    (ax.axhline if axis == "h" else ax.axvline)(value, **kw)


def figures_dir(lang: str) -> Path:
    d = PROJECT_ROOT / "manuscript" / lang / "ssrn" / "figures"
    d.mkdir(parents=True, exist_ok=True)
    return d


def save(fig, name: str, lang: str) -> Path:
    """Save a figure as PDF (for LaTeX) and PNG (for quick viewing) in the manuscript dir."""
    out = figures_dir(lang)
    fig.savefig(out / f"{name}.pdf", bbox_inches="tight", pad_inches=0.02)
    png = out / f"{name}.png"
    fig.savefig(png, bbox_inches="tight", pad_inches=0.02, dpi=200)
    plt.close(fig)
    return png
